{{- if .Values.bootstrapJob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-bootstrap-config
data:
  ibm_ops_agent_spyre_bootstrap_config.yaml: |-
{{ .Files.Get "config/ibm_ops_agent_spyre_bootstrap_config.yaml" | indent 4 }}
  ibm_ops_agent_granite.yaml: |-
{{ .Files.Get "config/ibm_ops_agent_granite.yaml" | indent 4 }}
{{- end }}