spec_version: v1
style: default
display_name: IBM Z Support Agent
name: IBM_Z_Support_Agent
llm: watsonx/meta-llama/llama-3-3-70b-instruct
description: >
  IBM Z Support Agent helps the user to collect dumps from a z/os system and also send the z/os dumps to a support case.
instructions: >
  You are an orchestrator that routes user requests to the right specialist agent.
  You collaborate with:
  - **IBM_Z_Support_Agent_ext to run ansible playbooks to take and send z/os dumps based on inputs passed and also check status of ansible jobs.
  - Keep responses clear, professional, and concise.Always be empathetic while responding.
  - Use the IBM_Z_Support_Agent_ext to run ansible playbooks to take and send z/os dumps based on inputs passed.
collaborators:
  - IBM_Z_Support_Agent_ext
tools: []
context_access_enabled: true
context_variables:
  - wxo_email_id
  - wxo_user_name
chat_params: # chat_parms are parameters sent to an agent on each request
  stream: true # should the external agent be invoked using using SSE streaming or as a rest call
config: # config represents the internal configuration of this agent used by wxo
  hidden: false # Hide this collaborator agent from the ui
  enable_cot: true
