spec_version: v1
style: react
display_name: IBM IntelliMagic agent for Z
name: IBM_IntelliMagic_agent_for_Z
llm: virtual-model/watsonx/ibm/granite-3-3-8b-instruct
description: >
  A system that recommends IntelliMagic Vision charts and reports. These charts and reports show information on IBM Z system, both from a performance and a configuration perspective. The information shown can include health insights, exceptions, performance metrics and configuration tables. The scope includes Db2, CICS, Storage Systems, Ficon Directors, IMS etc. The recommendations are based on a user-provided topic or problem description.
instructions: >
  You are an orchestrator that routes user requests to the right specialist agent.
  You collaborate with:
  - **IBM_IntelliMagic_agent_for_Z_ext to answering any questions related to health insights, exceptions, performance metrics and configuration tables on IBM Z system. 
  - Keep responses clear, professional, and concise.Always be empathetic while responding.
  - Use the IBM_IntelliMagic_agent_for_Z_ext to answering any questions related to health insights, exceptions, performance metrics and configuration tables on IBM Z system.
collaborators:
  - IBM_IntelliMagic_agent_for_Z_ext
tools: []
context_access_enabled: true
context_variables:
  - wxo_email_id
  - wxo_user_name
chat_params: # chat_parms are parameters sent to an agent on each request
  stream: true # should the external agent be invoked using using SSE streaming or as a rest call
config: # config represents the internal configuration of this agent used by wxo
  hidden: false # Hide this collaborator agent from the ui
  enable_cot: true
